
development:
  # password: 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
  # theme_id: "122745159838"
  # store: vital-body-therapeutics.myshopify.com

  password: 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
  theme_id: "123661615284"
  store: winifred-kriste-cake-classes.myshopify.com
